---
title: "Requested SitesLocations"
author: "Allan Kavuma"
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r LoadLibraries, echo=FALSE, message=FALSE, warning=FALSE}
## Site Link https://allankavuma.github.io/RequestedSiteLocations/SiteLocations
## Import Libraries
library(leaflet) ## Creating leaftlet map
library(xlsx) ## For reading excel file
library(dplyr) ## For data manipulation
```


```{r LoadData, echo=FALSE, message=FALSE, warning=FALSE}
## Read the data
## Read the site dataqqq
sitedata <- read.xlsx("SitesLocations.xls", sheetName = "UserData")
#sitedata1 <- read.xlsx("site.locations.xls", sheetName = "Sheet1")
```


```{r CleanData, echo=FALSE, message=FALSE, warning=FALSE}
## Clean the data
## Select the rows for the Latitudes, Longitudes and Region
siteLocations <- sitedata[,c("ATC.Number","ATC.Site.Name","Eaton.Name", "Sub.Region", 
                             "LATITUDE.DECIMAL", "LONGITUDE.DECIMAL")]
## Remove missing values data
siteLocations <- na.omit(siteLocations)
# Check if all missing values are removed
#table(is.na(siteLocations))
# Check the structure of the data frame
#str(siteLocations)
# Change Name variable from Factor to character type
siteLocations$ATC.Site.Name <- as.character(siteLocations$ATC.Site.Name)
## Remove wrong value of Mutara_House
siteLocations <- siteLocations[!(siteLocations$ATC.Site.Name == c("Mutara_House")),]
```


```{r PlotMap, echo = FALSE, message=FALSE, warning=FALSE,fig.width=16, fig.height=12}
## Plot the map
## Plot map according to the regions of the sites
leaflet(siteLocations) %>% addTiles() %>% addMarkers(lat = siteLocations$LATITUDE.DECIMAL, lng = siteLocations$LONGITUDE.DECIMAL, popup = paste("SiteName:" = siteLocations$ATC.Site.Name, "</br>",
                                                                                                                              "ATC SiteID:" = siteLocations$ATC.Number, "</br>",
                            "Eaton SiteID:" = siteLocations$Eaton.Name, "</br>",
                            "Sub Region" = siteLocations$Sub.Region),                                                                                                  
                                                                                                                              clusterOptions = markerClusterOptions())

leaflet(siteLocations) %>% addTiles() %>% addCircles(lat = siteLocations$LATITUDE.DECIMAL, lng = siteLocations$LONGITUDE.DECIMAL, weight = 20, popup = paste("SiteName:" = siteLocations$ATC.Site.Name, "</br>",
                                                                                                                              "ATC SiteID:" = siteLocations$ATC.Number, "</br>",
                            "Eaton SiteID:" = siteLocations$Eaton.Name))


#leaflet(siteLocations) %>%
#  addTiles() %>%
#  addCircles(lat = siteLocations$Latitude, lng = siteLocations$Longitude, weight = 1, 
#              popup = paste("SiteName:" = siteLocations$Site.name, "</br>",                                                      "SiteID:" = siteLocations$Site.ID  ), 
#             color = ~pal(Regional.Supervisor), radius = 5000) %>%
#    addLegend(pal = pal, values = ~siteLocations$Regional.Supervisor, group = "circles", position = "bottomright")
```